spring.application.name=Docker Compose
# Lokal MySQL ayarlar?
spring.datasource.url=jdbc:mysql://localhost:3306/devops_db
spring.datasource.username=root
spring.datasource.password=revan123
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
